apiVersion: v1
kind: Service
metadata:
  name: nginxdemos
  namespace: eks-blueprint-test
  labels:
    name: nginxdemos
  annotations:
    omnideqname: nginx-blueprint(app)->nginx-blueprint(blueprint)->nginx(dep)->nginxdemos(service)-loadbalancer(service-type)-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginxdemos-port0
