kind: Deployment
apiVersion: apps/v1
metadata:
  name: eks-bp-deployment-2
  namespace: eks-bp-ns
  labels:
    name: eks-bp-deployment-2
  annotations:
    omnideqname: eshop-1(app)->eshop-1(blueprint)->eks-bp-deployment-2(dep)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-bp-deployment-2
  template:
    metadata:
      labels:
        app: eks-bp-deployment-2
      annotations: {}
    spec:
      containers:
        - name: nginx-helloworld
          image: dockerbogo/docker-nginx-hello-world:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom: []
          volumeMounts: []
      volumes: []
      hostAliases: []
      imagePullSecrets: []
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 30
