apiVersion: v1
kind: Service
metadata:
  name: nginx-helloworld
  namespace: eks-bp-ns
  labels:
    name: nginx-helloworld
  annotations:
    omnideqname: eshop-1(app)->eshop-1(blueprint)->eks-bp-deployment-2(dep)->nginx-helloworld(service)-loadbalancer(service-type)-service
spec:
  type: LoadBalancer
  selector:
    app: eks-bp-deployment-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx-helloworld-port0
