kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: eks-blueprint-test
  labels:
    name: nginx
  annotations:
    omnideqname: nginx-blueprint(app)->nginx-blueprint(blueprint)->nginx(dep)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations: {}
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom: []
          volumeMounts: []
      volumes: []
      hostAliases: []
      imagePullSecrets: []
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 30
